Fix "implicit declaration of function" issue
It show "implicit declaration of function" wrong mesasge,
In general speaking, it is defined in the C file where
the function is located, but it is not declared in the
associated H file, I refer to another project, this change
is same with other project fixed this issue.

Change-Id: I220758dbae547567cb9a2f53a42ff9e05dedc421
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-41262
Signed-off-by: Liu, Wei-nan <wei-nan.liu@intel.com>
               Yonghuax, Fu <yonghuax.fu@intel.com>
Reviewed-on: https://android.intel.com:443/558355